"""multi-currency: fx_rates + transaction base_amount

Revision ID: 9640ebc219d0
Revises: 6adf6d886c0f
Create Date: 2026-05-31 18:22:44.552452
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9640ebc219d0'
down_revision: Union[str, None] = '6adf6d886c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('base', sa.String(length=3), nullable=False),
    sa.Column('quote', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_date', 'base', 'quote', name='uq_fx_rate')
    )
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fx_rates_rate_date'), ['rate_date'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_amount', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), nullable=True))
        batch_op.add_column(sa.Column('fx_source', sa.String(length=32), nullable=True))
        # server_default avoids a NOT NULL failure on existing rows.
        batch_op.add_column(
            sa.Column('needs_rate', sa.Boolean(), nullable=False, server_default=sa.text('0'))
        )

    # Backfill: existing transactions pre-date multi-currency and were treated
    # as already being in the base currency, so base_amount = amount, rate = 1.
    op.execute("UPDATE transactions SET base_amount = amount, fx_rate = 1, fx_source = 'legacy' "
               "WHERE base_amount IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('needs_rate')
        batch_op.drop_column('fx_source')
        batch_op.drop_column('fx_rate')
        batch_op.drop_column('base_amount')

    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fx_rates_rate_date'))

    op.drop_table('fx_rates')
    # ### end Alembic commands ###
