// Generate the data the "Spending by location" world map renders:
//   frontend/src/data/world_land.ts      — per-country SVG paths (fill + borders)
//   frontend/src/data/country_centroids.ts — { ISO-2: [lat, lng] } for plotting points
//
// Both are GENERATED (do not hand-edit) so we don't ship a heavy map library or
// hand-maintain ~250 coordinates. The country paths and the centroids share the
// same cropped equirectangular projection, so plotted points line up with the map.
//
// The projection is CROPPED to ~83°N…−56°S and Antarctica is dropped — full −90..90
// equirectangular squashes the poles into ugly horizontal streaks. Per-country
// geometry (countries-110m, not land-110m) gives us borders + a future choropleth.
//
// One-off dev step (the generated files are committed; these packages are NOT
// runtime deps):  npm i --no-save world-atlas topojson-client world-countries
// Then from the repo root:  node scripts/gen_worldmap.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";

// Cropped equirectangular projection. Longitude spans the full −180..180; latitude
// is clipped to the populated band so the poles don't streak. Height keeps the
// band roughly to scale.
const W = 1000;
const LAT_TOP = 83;
const LAT_BOTTOM = -56;
const H = Math.round((W * (LAT_TOP - LAT_BOTTOM)) / 360);
const project = (lon, lat) => [
  Math.round(((lon + 180) / 360) * W),
  Math.round(((LAT_TOP - lat) / (LAT_TOP - LAT_BOTTOM)) * H),
];

function ringToPath(ring) {
  let d = "";
  let prev = null;
  for (const [lon, lat] of ring) {
    const [x, y] = project(lon, lat);
    if (prev?.[0] === x && prev?.[1] === y) continue; // drop points that round together
    d += (d ? "L" : "M") + x + " " + y;
    prev = [x, y];
  }
  return d ? d + "Z" : "";
}

function geometryToPath(geom) {
  const polys = geom.type === "MultiPolygon" ? geom.coordinates : [geom.coordinates];
  return polys.flatMap((poly) => poly.map(ringToPath)).filter(Boolean).join("");
}

// --- Countries → one SVG path each (fill + borders) -------------------------
const topo = JSON.parse(readFileSync("node_modules/world-atlas/countries-110m.json", "utf8"));
const fc = feature(topo, topo.objects.countries);
const ANTARCTICA = "010"; // numeric ISO id — squashed band at the bottom, dropped
const countryPaths = fc.features
  .filter((f) => f.id !== ANTARCTICA && f.geometry)
  .map((f) => geometryToPath(f.geometry))
  .filter(Boolean);

const landHeader =
  "// World country outlines — GENERATED by scripts/gen_worldmap.mjs (do not hand-edit).\n" +
  "// Cropped equirectangular (" + W + "x" + H + ", " + LAT_TOP + "°N…" + LAT_BOTTOM +
  "°S, Antarctica dropped); consumed by WorldMap.tsx.\n\n";
writeFileSync(
  "frontend/src/data/world_land.ts",
  landHeader +
    "export const WORLD_W = " + W + ";\n" +
    "export const WORLD_H = " + H + ";\n" +
    "export const WORLD_LAT_TOP = " + LAT_TOP + ";\n" +
    "export const WORLD_LAT_BOTTOM = " + LAT_BOTTOM + ";\n" +
    "export const WORLD_COUNTRY_PATHS: string[] = [\n" +
    countryPaths.map((d) => "  " + JSON.stringify(d) + ",").join("\n") +
    "\n];\n",
  "utf8",
);

// --- Country centroids { ISO-2: [lat, lng] } --------------------------------
const countries = JSON.parse(readFileSync("node_modules/world-countries/countries.json", "utf8"));
const centroids = {};
for (const c of countries) {
  if (c.cca2 && Array.isArray(c.latlng) && c.latlng.length === 2) {
    centroids[c.cca2] = [Number(c.latlng[0].toFixed(2)), Number(c.latlng[1].toFixed(2))];
  }
}

const centHeader =
  "// Country centroids [lat, lng] by ISO-3166-1 alpha-2 — GENERATED by\n" +
  "// scripts/gen_worldmap.mjs (do not hand-edit). Used to plot points on the map.\n\n";
writeFileSync(
  "frontend/src/data/country_centroids.ts",
  centHeader + "export const COUNTRY_CENTROIDS: Record<string, [number, number]> =\n" +
    JSON.stringify(centroids, null, 2) + ";\n",
  "utf8",
);

console.log("country paths:", countryPaths.length, "| total path chars:", countryPaths.join("").length);
console.log("country_centroids.ts entries:", Object.keys(centroids).length);
