// Generate the data the "Spending by location" world map renders:
//   frontend/src/data/world_land.ts      — one SVG path of the world's landmass
//   frontend/src/data/country_centroids.ts — { ISO-2: [lat, lng] } for plotting points
//
// Both are GENERATED (do not hand-edit) so we don't ship a heavy map library or
// hand-maintain ~250 coordinates. The land outline and the centroids share the
// same equirectangular projection, so plotted points line up with the coastline.
//
// One-off dev step (the generated files are committed; these packages are NOT
// runtime deps):  npm i --no-save world-atlas topojson-client world-countries
// Then from the repo root:  node scripts/gen_worldmap.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";

// Equirectangular projection onto a WIDTH x HEIGHT canvas (lon -180..180 → 0..W,
// lat 90..-90 → 0..H). Kept deliberately small; integer rounding collapses the
// coarse 110m coastline to a compact path that still reads as a world map.
const W = 1000;
const H = 500;
const project = (lon, lat) => [Math.round(((lon + 180) / 360) * W), Math.round(((90 - lat) / 180) * H)];

// --- World landmass → a single SVG path -------------------------------------
const landTopo = JSON.parse(readFileSync("node_modules/world-atlas/land-110m.json", "utf8"));
const land = feature(landTopo, landTopo.objects.land);

function ringToPath(ring) {
  let d = "";
  let prev = null;
  for (const [lon, lat] of ring) {
    const [x, y] = project(lon, lat);
    if (prev?.[0] === x && prev?.[1] === y) continue; // drop points that round together
    d += (d ? "L" : "M") + x + " " + y;
    prev = [x, y];
  }
  return d ? d + "Z" : "";
}

// feature() yields a Feature or a FeatureCollection depending on the object;
// normalise to a flat list of geometries, then to a flat list of polygons.
const geometries = land.type === "FeatureCollection" ? land.features.map((f) => f.geometry) : [land.geometry];
const landPath = geometries
  .flatMap((g) => (g.type === "MultiPolygon" ? g.coordinates : [g.coordinates]))
  .flatMap((poly) => poly.map(ringToPath))
  .filter(Boolean)
  .join("");

const landHeader =
  "// World landmass outline — GENERATED by scripts/gen_worldmap.mjs (do not hand-edit).\n" +
  "// Equirectangular projection on a " + W + "x" + H + " canvas; consumed by WorldMap.tsx.\n\n";
writeFileSync(
  "frontend/src/data/world_land.ts",
  landHeader +
    "export const WORLD_W = " + W + ";\n" +
    "export const WORLD_H = " + H + ";\n" +
    "export const WORLD_LAND_PATH =\n  " + JSON.stringify(landPath) + ";\n",
  "utf8",
);

// --- Country centroids { ISO-2: [lat, lng] } --------------------------------
const countries = JSON.parse(readFileSync("node_modules/world-countries/countries.json", "utf8"));
const centroids = {};
for (const c of countries) {
  if (c.cca2 && Array.isArray(c.latlng) && c.latlng.length === 2) {
    centroids[c.cca2] = [Number(c.latlng[0].toFixed(2)), Number(c.latlng[1].toFixed(2))];
  }
}

const centHeader =
  "// Country centroids [lat, lng] by ISO-3166-1 alpha-2 — GENERATED by\n" +
  "// scripts/gen_worldmap.mjs (do not hand-edit). Used to plot points on the map.\n\n";
writeFileSync(
  "frontend/src/data/country_centroids.ts",
  centHeader + "export const COUNTRY_CENTROIDS: Record<string, [number, number]> =\n" +
    JSON.stringify(centroids, null, 2) + ";\n",
  "utf8",
);

console.log("world_land.ts path length:", landPath.length, "chars");
console.log("country_centroids.ts entries:", Object.keys(centroids).length);
